# Generated by Django 4.0.1 on 2022-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='artists/'),
        ),
        migrations.AlterIndexTogether(
            name='artist',
            index_together={('id', 'slug')},
        ),
    ]
