# Generated by Django 4.0.3 on 2022-04-05 15:27

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_albumratingbyuser_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumratingbyuser',
            name='ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]), blank=True, size=None),
        ),
    ]
