# Generated by Django 4.0.3 on 2022-04-09 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_albumratingbyuser_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumratingbyuser',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
            preserve_default=False,
        ),
    ]
