# Generated by Django 4.0.3 on 2022-04-10 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_alter_usersalbumrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
        migrations.AlterField(
            model_name='usersalbumrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AlbumRatingByUser',
        ),
    ]
