# Generated by Django 4.0.3 on 2022-07-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
