# Generated by Django 4.0.3 on 2022-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_album_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
